FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S spring && adduser -S spring -G spring
ENV SPRING_PROFILES_ACTIVE=docker
ARG SERVICE_PATH
COPY ${SERVICE_PATH}/build/libs/*.jar app.jar
USER spring:spring
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
