---
# promotion-service — STAGE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: circleguard-stage
  labels: {app: promotion-service, env: stage}
spec:
  replicas: 2
  selector:
    matchLabels: {app: promotion-service}
  template:
    metadata:
      labels: {app: promotion-service, env: stage}
    spec:
      containers:
      - name: promotion-service
        image: circleguard/promotion-service:stage-latest
        imagePullPolicy: Never
        ports: [{containerPort: 8088}]
        env:
        - {name: SPRING_DATASOURCE_URL, value: "jdbc:postgresql://postgres-svc.circleguard-stage.svc.cluster.local:5432/circleguard_promotion"}
        - {name: SPRING_DATASOURCE_USERNAME, value: admin}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: {secretKeyRef: {name: circleguard-secrets, key: POSTGRES_PASSWORD}}
        - {name: SPRING_NEO4J_URI, value: "bolt://neo4j-svc.circleguard-stage.svc.cluster.local:7687"}
        - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
          valueFrom: {secretKeyRef: {name: circleguard-secrets, key: NEO4J_PASSWORD}}
        - {name: SPRING_KAFKA_BOOTSTRAP_SERVERS, value: "kafka-svc.circleguard-stage.svc.cluster.local:9092"}
        - {name: SPRING_DATA_REDIS_HOST, value: "redis-svc.circleguard-stage.svc.cluster.local"}
        - name: JWT_SECRET
          valueFrom: {secretKeyRef: {name: circleguard-secrets, key: JWT_SECRET}}
        readinessProbe:
          httpGet: {path: /actuator/health, port: 8088}
          initialDelaySeconds: 50
          periodSeconds: 10
          failureThreshold: 6
        resources:
          requests: {memory: "512Mi", cpu: "400m"}
          limits: {memory: "1Gi", cpu: "800m"}
---
apiVersion: v1
kind: Service
metadata:
  name: promotion-service-svc
  namespace: circleguard-stage
spec:
  selector: {app: promotion-service}
  ports: [{port: 8088, targetPort: 8088, nodePort: 31088}]
  type: NodePort
